/// Flutter icons IcIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IcIcons
///      fonts:
///       - asset: fonts/IcIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IcIcons {
  IcIcons._();

  static const _kFontFam = 'IcIcons';

  static const IconData price = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData date = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe804, fontFamily: _kFontFam);
}
